#!/usr/bin/env python3
"""Emit all_errors.rs for the oracle (main.rs `include!`): every PercolatorError variant as
(name, E::Name as u32). The NAMES come from the enum's source text; the ORDINALS are computed
by rustc (`as u32`), so a mis-parse fails to compile or mismatches, it cannot silently lie.
  python3 gen-all-errors.py <percolator-prog>/src/v16_program.rs > <oracle>/src/all_errors.rs
"""
import re, sys
src = open(sys.argv[1]).read()
i = src.index("pub enum PercolatorError")
j = src.index("\n    }", i)
names = []
for line in src[i:j].split("\n")[1:]:
    l = re.sub(r"//.*", "", line).strip()
    if not l or l.startswith("#"):
        continue
    for tok in l.split(","):
        t = tok.strip()
        if re.match(r"^[A-Z][A-Za-z0-9]*$", t):
            names.append(t)
print("// GENERATED by gen-all-errors.py; do not edit.")
print("fn all_errors() -> Vec<(&'static str, u32)> {")
print("    vec![")
for n in names:
    print(f'        ("{n}", E::{n} as u32),')
print("    ]")
print("}")
